/* tslint:disable:max-line-length completed-docs variable-name*/

export const TerminalHelpText: string[] = [
  "Type 'help name' to learn more about the command ",
  " ",
  '    alias [-g] [name="value"]            Créé ou affiche les alias du Terminal',
  "    analyze                              Obtenir des informations sur la machine actuelle ",
  "    backdoor                             Installer une porte dérobée sur la machine en cours ",
  "    buy [-l/-a/program]                  Acheter un programme via le Dark Web",
  "    cat [file]                           Afficher un fichier .msg, .lit ou .txt",
  "    cd [dir]                             Changer pour un nouveau répertoire",
  "    check [script] [args...]             Afficher les journaux d'un script sur Terminal",
  "    clear                                Effacer tout le texte sur le terminal ",
  "    cls                                  Voir la commande 'clear' ",
  "    connect [hostname]                   Se connecte à un serveur distant",
  "    cp [src] [dst]                       Copier un fichier",
  "    download [script/text file]          Télécharge des scripts ou des fichiers texte sur votre ordinateur",
  "    expr [math expression]               Évaluer une expression mathématique",
  "    free                                 Vérifiez l'utilisation de la mémoire (RAM) de la machine",
  "    grow                                 Faux de l'argent sur le compte bancaire d'un serveur, augmentant le montant disponible.",
  "    hack                                 Hackez la machine actuelle",
  "    help [command]                       Afficher ce texte d'aide ou le texte d'aide d'une commande",
  "    history [-c]                         Afficher l'historique du terminal",
  "    home                                 Connectez-vous à l'ordinateur personnel",
  "    hostname                             Affiche le nom d'hôte de la machine",
  "    kill [script/pid] [args...]          Arrête le script spécifié sur le serveur en cours ",
  "    killall                              Arrête tous les scripts en cours d'exécution sur la machine actuelle",
  "    ls [dir] [--grep pattern]            Affiche tous les fichiers sur la machine",
  "    lscpu                                Affiche le nombre de cœurs de processeur sur la machine",
  "    mem [script] [-t n]                  Affiche la quantité de RAM nécessaire pour exécuter le script",
  "    mv [src] [dest]                      Déplacer/renommer un fichier texte ou script",
  "    nano [file ...]                      Éditeur de texte - Ouvrez et modifiez un ou plusieurs scripts ou fichiers texte",
  "    ps                                   Afficher tous les scripts en cours d'exécution",
  "    rm [file]                            Supprimer un fichier du serveur",
  "    run [name] [-t n] [--tail] [args...] Exécuter un programme ou un script",
  "    scan                                 Affiche toutes les connexions réseau immédiatement disponibles",
  "    scan-analyze [d] [-a]                Affiche les informations pour tous les serveurs jusqu'à d nœuds",
  "    scp [file ...] [server]              Copie un fichier sur un serveur de destination",
  "    sudov                                Indique si vous avez un accès root sur cet ordinateur",
  "    tail [script] [args...]              Affiche les journaux dynamiques pour le script spécifié",
  "    top                                  Affiche tous les scripts en cours d'exécution et leur utilisation de la RAM",
  "    unalias [alias name]                 Supprime l'alias spécifié",
  "    vim [file ...]                       Éditeur de texte - Ouvrez et modifiez un ou plusieurs scripts ou fichiers texte en mode vim",
  "    weaken                               Réduire la sécurité de la machine actuelle",
  "    wget [url] [target file]             Récupère le code/texte d'un serveur Web",
  " ",
];

const TemplatedHelpTexts: Record<string, (command: string) => string[]> = {
  scriptEditor: (command) => {
    return [
      `Utilisation: ${command} [file ...] | [glob]`,
      ` `,
      `Ouvre le(s) fichier(s) spécifié(s) dans l'éditeur de script. Seuls les scripts (.js ou .script) ou les fichiers texte (.txt) `,
      `peut être modifié à l'aide de l'éditeur de script. Si un fichier n'existe pas, un nouveau sera créé`,
      ` `,
      `Si un glob est fourni comme seul argument, ${command} peut parcourir les répertoires et ouvrir tous les ` correspondants,
      `fichiers à la fois. ${command} ne peut pas créer de fichiers à l'aide de globs, vos scripts doivent donc déjà exister.`,
      ` `,
      `Examples:`,
      ` `,
      `    ${command} test.js`,
      `    ${command} test.js test2.js`,
      ` `,
      `    ${command} test.*`,
      `    ${command} /my-dir/*.js`,
      ` `,
    ];
  },
};

export const HelpTexts: Record<string, string[]> = {
  alias: [
    'Utilisation: alias [-g] [name="value"] ',
    " ",
    "Créer ou afficher des alias. Un alias permet de remplacer un mot par une autre chaîne. ",
    "Il peut être utilisé pour abréger une commande couramment utilisée, ou des parties couramment utilisées d'une commande. Le NOM ",
    "d'un alias définit le mot qui sera remplacé, tandis que la VALEUR définit par quoi il sera remplacé. Par exemple, ",
    "vous pouvez créer l'alias 'nuke' pour la commande Terminal 'run NUKE.exe' en utilisant ce qui suit : ",
    " ",
    ' alias nuke="exécuter NUKE.exe"',
    " ",
    "Ensuite, pour exécuter le programme NUKE.exe, il vous suffirait d'entrer 'nuke' dans Terminal plutôt que la commande complète. ",
    "Il est important de noter que les alias 'par défaut' ne seront remplacés que par le premier mot d'une commande Terminal. Pour ",
    "exemple, si l'alias suivant a été défini : ",
    " ",
    ' alias ver="HTTPWorm.exe"',
    " ",
    "puis vous avez essayé d'exécuter la commande de terminal suivante : ",
    " ",
    « courir ver »,
    " ",
    "Cela échouerait car l'alias du ver n'est pas le premier mot d'une commande Terminal. Pour autoriser le remplacement d'un alias ",
    "n'importe où dans une commande Terminal, plutôt que juste le premier mot, vous devez le définir comme un alias global à l'aide de l'indicateur -g : ",
    " ",
    ' alias -g worm="Ver HTTP.exe"',
    " ",
    "Maintenant, l'alias 'ver' sera remplacé chaque fois qu'il apparaîtra comme un mot individuel dans une commande Terminal.",
    " ",
    "Saisir uniquement la commande 'alias' sans aucun argument Affiche la liste de tous les alias définis sous la forme réutilisable ",
    "'alias NAME=VALUE' sur le Terminal. ",
    " ",
    "La commande 'unalias' peut être utilisée pour supprimer des alias.",
    " ",
  ],
  analyze: [
    "Utilisation: analyze",
    " ",
    "Affiche les détails et les statistiques sur le serveur actuel. Les informations imprimées incluent les informations de base ",
    "les détails du serveur tels que le nom d'hôte, si le joueur a un accès root, quels ports sont ouverts/fermés, et aussi ",
    "des informations liées au piratage telles qu'une chance estimée de réussir un piratage, une estimation du montant d'argent ",
    "disponible sur le serveur, etc.",
    " ",
  ],
  backdoor: [
    "Utilisation: backdoor",
    " ",
    "Installer une porte dérobée sur la machine actuelle, accorde un bonus secret en fonction de la machine.",
    " ",
    "Nécessite un accès root pour s'exécuter.",
    " ",
  ],
  buy: [
    "Utilisation: buy [-l / -a / program]",
    " ",
    "Achetez un programme via le Dark Web. Nécessite l'utilisation d'un routeur TOR.",
    " ",
    "Si cette commande est exécutée avec le drapeau '-l', elle affichera une liste de tous les programmes pouvant être achetés via le ",
    "du dark web au Terminal, ainsi que leurs coûts.",
    " ",
    "Si cette commande est exécutée avec le drapeau '-a', elle tentera d'acheter tous les programmes sans propriétaire.",
    " ",
    "Sinon, le nom du programme doit être passé en paramètre. Ce nom n'est PAS sensible à la casse.",
    " ",
  ],
  cat: [
    "Utilisation: cat [file]",
    " ",
    "Display message (.msg), literature (.lit), or text (.txt) files. Examples:",
    " ",
    "    cat j1.msg",
    " ",
    "    cat foo.lit",
    " ",
    "    cat servers.txt",
    " ",
  ],
  cd: [
    "Utilisation: cd [dir]",
    " ",
    "Passez au répertoire spécifié. Notez que cela fonctionne même pour les répertoires qui n'existent pas. Si vous ",
    "passez à un répertoire qui n'existe pas, il ne sera pas 'créé'. Exemples :",
    " ",
    "    cd scripts/hacking",
    " ",
    "    cd /logs",
    " ",
    "    cd ../",
    " ",
  ],
  check: [
    "Utilisation: check [script name] [args...]",
    " ",
    "Affiche les journaux du script spécifié par le nom du script et les arguments sur le Terminal. Chaque argument doit être séparé par ",
    "un espace. N'oubliez pas qu'un script en cours d'exécution est unique ",
    "identifié à la fois par son nom et les arguments utilisés pour le démarrer. Ainsi, si un script a été exécuté avec les arguments suivants : ",
    " ",
    "    run foo.script 1 2 foodnstuff",
    " ",
    "Ensuite, pour exécuter la commande 'check' sur ce script, vous devrez passer les mêmes arguments dans : ",
    " ",
    "    check foo.script 1 2 foodnstuff",
    " ",
  ],
  clear: [
    "Utilisation: clear",
    " ",
    "Effacez l'écran du terminal, en supprimant tout le texte. Notez que cela ne supprime pas l'historique des commandes de l'utilisateur, utilisez donc le haut ",
    "et les touches fléchées vers le bas sont toujours valides. Notez également que cela est permanent et qu'il n'y a aucun moyen de l'annuler. Synonyme de la commande 'cls'",


    " ",
  ],
  cls: [
    "Utilisation: cls",
    " ",
    "Effacez l'écran du terminal, en supprimant tout le texte. Notez que cela ne supprime pas l'historique des commandes de l'utilisateur, utilisez donc le haut ",
    "et les touches fléchées vers le bas sont toujours valides. Notez également que cela est permanent et qu'il n'y a aucun moyen de l'annuler. Synonyme de la commande 'clear'",
    " ",
  ],
  connect: [
    "Utilisation: connect [hostname]",
    " ",
    "Se connecter à un serveur distant. Le nom d'hôte du serveur distant doit être donné en argument",
    "à cette commande. Notez que seuls les serveurs qui sont immédiatement adjacents au serveur actuel dans le réseau et ceux qui ont",
    "une porte dérobée installée peut être connectée. Pour voir à quels serveurs peuvent être connectés, utilisez la commande 'scan'.",
    " ",
  ],
  cp: ["Utilisation: cp [src] [dst]", " ", "Copy a file on this server. To copy a file to another server use scp.", " "],
  download: [
    "Utilisation: download [script/text file]",
    " ",
    "Télécharge un script ou un fichier texte sur votre ordinateur (comme votre ordinateur réel).",
    " ",
    "Vous pouvez également télécharger tous vos scripts/fichiers texte sous forme de fichier zip à l'aide des commandes Terminal suivantes :",
    " ",
    "Télécharger tous les scripts et fichiers texte : télécharger *",
    " ",
    "Télécharger tous les scripts : télécharger *.script",
    " ",
    "Télécharger tous les fichiers texte : télécharger *.txt",
    " ",
  ],
  expr: [
    "Utilisation: expr [mathematical expression]",
    " ",
   "Évaluer une expression mathématique simple. Prend en charge les opérateurs JavaScript natifs :",
    " ",
    "+, -, /, *, **, %",
    " ",
    "Exemple:",
    " ",
    "    expr 25 * 2 ** 10",
    " ",
    "Notez que les lettres (autres que les chiffres) ne sont pas autorisées et seront supprimées de l'entrée.",
    " ",
  ],
  free: [
    "Utilisation: free",
    " ",
    "Affiche l'utilisation de la mémoire sur la machine actuelle. Affiche la quantité de RAM disponible sur le serveur actuel ainsi que ",
    "quelle quantité est utilisée.",
    " ",
  ],
  grow: [
    "Utilisation: grow",
    " ",
    "Transactions frauduleuses sur le serveur actuel. Augmenter l'argent disponible en piratant. Nécessite un accès root.",
    "Voir la page wiki pour les mécanismes de piratage.",
    " ",
  ],
  hack: [
    "Utilisation: hack",
    " ",
    "Essayer de pirater le serveur actuel. Nécessite un accès root pour être exécuté. Voir la page wiki pour les mécanismes de piratage",
    " ",
  ],
  help: [
    "Utilisation: help [command]",
    " ",
    "Afficher les informations d'aide du terminal. Sans arguments, 'help' Affiche une liste de toutes les commandes valides du terminal et un bref ",
    "description de leurs fonctionnalités. Vous pouvez également passer le nom d'une commande Terminal en argument à 'help' pour Afficher",
    "informations plus détaillées sur la commande Terminal. Exemples : ",
    " ",
    "    help alias",
    " ",
    "    help scan-analyze",
    " ",
  ],
  history: [
    "Utilisation: history [-c]",
    " ",
    "Sans arguments, affiche l'historique des commandes du terminal. Pour effacer l'historique, passez l'argument '-c'.",
    " ",
  ],
  home: [
    "Utilisation: home",
    " ",
    "Connectez-vous à votre ordinateur personnel. Cela fonctionnera quel que soit le serveur auquel vous êtes actuellement connecté.",
    " ",
  ],
  hostname: ["Utilisation: hostname", " ", "Prints the hostname of the current server", " "],
  kill: [
    "Utilisation: kill [script name] [args...] or kill [pid",
    " ",
    "Tuez le script spécifié par le nom du script et les arguments OU par son PID.",
    " ",
    "Si vous tuez le script en utilisant son nom de fichier et ses arguments, alors chacun ",
    "l'argument doit être séparé par un espace. N'oubliez pas qu'un script en cours d'exécution est ",
    "identifié de manière unique à la fois par son nom et par les arguments utilisés pour démarrer ",
    "it. Ainsi, si un script a été exécuté avec les arguments suivants :",
    " ",
    " run foo.script 1 sigma-cosmetics",
    " ",
    "Ensuite, pour tuer ce script, les mêmes arguments devraient être utilisés :",
    " ",
    " kill foo.script 1 sigma-cosmétique",
    " ",
    "Si vous tuez le script en utilisant son PID, alors l'argument PID doit être numérique",
    " ",
  ],
  killall: [
    "Utilisation: killall",
    " ",
    "Tue tous les scripts sur le serveur actuel. ",
    "Notez qu'après l'émission de la commande 'kill' pour un script, cela peut prendre un certain temps pour que le script s'arrête réellement. ",
    "Cela se produira si le script est au milieu d'une commande telle que grow() ou affaibli() qui prend du temps à s'exécuter.",
    "Le script ne sera pas arrêté/tué tant que ce temps ne sera pas écoulé.",
    " ",
  ],
  ls: [
    "Utilisation: ls [dir] [-l] [--grep pattern]",
    " ",
    "La commande ls, sans arguments, Affiche tous les fichiers et répertoires du répertoire du serveur actuel sur l'écran du terminal.",
    "Les fichiers seront affichés par ordre alphabétique. ",
    " ",
    "Le paramètre optionnel 'dir' peut être utilisé pour afficher des fichiers/répertoires dans un autre répertoire.",
    " ",
    "Le paramètre optionnel '-l' permet de forcer chaque élément sur une seule ligne.",
    " ",
    "Le paramètre facultatif '--grep pattern' peut être utilisé pour afficher uniquement les fichiers dont les noms correspondent au modèle spécifié.",
    " ",
    "Exemples:",
    " ",
    "Liste tous les fichiers avec l'extension '.script' dans le répertoire courant :",
    " ",
    " ls -l --grep .script",
    " ",
    "Liste tous les fichiers avec l'extension '.js' dans le répertoire racine :",
    " ",
    " ls / -l --grep .js",
    " ",
    "Liste tous les fichiers avec le mot 'achat' dans le nom du fichier, dans le répertoire 'scripts' :",
    " ",
    " ls scripts -l --grep achat",
    " ",
  ],
  lscpu: ["Utilisation: lscpu", " ", "Prints the number of CPU Cores the current server has", " "],

  mem: [
    "Utilisation: mem [script name] [-t num_threads]",
    " ",
    "Affiche la quantité de RAM nécessaire pour exécuter le script spécifié avec un seul thread. La commande peut également être utilisée pour Afficher ",
    "la quantité de RAM nécessaire pour exécuter un script avec plusieurs threads à l'aide de l'indicateur '-t'. Si l'indicateur '-t' est spécifié, alors ",
    "un argument pour le nombre de threads doit être passé ensuite. Exemples :",
    " ",
    " mem foo.script",
    " ",
    " mem foo.script -t 50",
    " ",
    "Le premier exemple ci-dessus affichera la quantité de RAM nécessaire pour exécuter 'foo.script' avec un seul thread. Le deuxième exemple ",
    "ci-dessus affichera la quantité de RAM nécessaire pour exécuter 'foo.script' avec 50 threads.",
    " ",
  ],
  mv: [
    "Utilisation: mv [src] [dest]",
    " ",
    "Déplacez le fichier source vers la destination spécifiée. Cela peut également être utilisé pour renommer des fichiers. ",
    "Cette commande ne fonctionne que pour les scripts et les fichiers texte (.txt). Cette commande NE PEUT PAS être utilisée pour ",
    "convertir en différents types de fichiers",
    " ",
    "Notez que, contrairement à la commande Linux 'mv', l'argument de destination doit être ",
    "chemin complet du fichier. ",
    "Exemples: ",
    " ",
    "    mv hacking-controller.script scripts/hacking-controller.script",
    " ",
    "    mv myScript.js myOldScript.js",
    " ",
  ],
  nano: TemplatedHelpTexts.scriptEditor("nano"),
  ps: ["Utilisation: ps", " ", "Affiche tous les scripts en cours d'exécution sur le serveur actuel", " "],
  rm: [
    "Utilisation: rm [file]",
    " ",
    "Supprime le fichier spécifié du serveur actuel. Un fichier peut être un script, un programme ou un fichier de message. ",
    " ",
    "AVERTISSEMENT : Ceci est permanent et ne peut pas être annulé",
    " ",
  ],
  run: [
    "Utilisation: run [file name] [-t] [num threads] [args...]",
    " ",
    "Exécuter un programme, un script ou un contrat de codage.",
    " ",
    "Les arguments '[-t]', '[num threads]' et '[args...]' ne sont valides que lors de l'exécution d'un script. Le drapeau '-t' est utilisé ",
    "pour indiquer que le script doit être exécuté avec le nombre de threads spécifié. Si l'indicateur est omis, ",
    "alors le script sera exécuté avec un seul thread par défaut. ",
    "Si le drapeau '-t' est utilisé, il DOIT venir immédiatement ",
    "après le nom du script, et l'argument [num threads] DOIT venir immédiatement après. ",
    " ",
    "[args...] représente un nombre variable d'arguments qui seront passés dans le script. Voir la documentation ",
    "à propos des arguments de script. Chaque argument spécifié doit être séparé par un espace. ",
    " ",
  ],
  scan: [
    "Utilisation: scan",
    " ",
    "Affiche toutes les connexions réseau immédiatement disponibles. Cela Affichera une liste de tous les serveurs auxquels vous pouvez actuellement vous connecter ",
    "pour utiliser la commande 'connect' Terminal.",
    " ",
  ],
  "scan-analyze": [
    "Utilisation: scan-analyze [depth] [-a]",
    " ",
    "Affiche des informations détaillées sur tous les serveurs jusqu'aux nœuds [de profondeur] sur le réseau. Appel ",
    "'scan-analyze 1' affichera des informations pour les mêmes serveurs que ceux affichés par le terminal 'scan' ",
    "commande. Cette commande affiche également les chemins relatifs pour atteindre chaque serveur.",
    " ",
    "Par défaut, la profondeur maximale pouvant être spécifiée pour 'scan-analyze' est de 3. Cependant, une fois que vous avez ",
    "les programmes DeepscanV1.exe et DeepscanV2.exe, vous pouvez exécuter 'scan-analyze' avec une profondeur allant jusqu'à ",
    "5 et 10, respectivement.",
    " ",
    "Les informations 'scan-analyze' affichées sur chaque serveur incluent si vous avez ou non un accès root à celui-ci", ",
    "son niveau de piratage requis, le nombre de ports ouverts requis pour exécuter NUKE.exe dessus et la quantité de RAM",
    "il a.",
    " ",
    "Par défaut, cette commande n'affichera pas les serveurs que vous avez achetés. Cependant, vous pouvez passer le ",
    "-un indicateur à la fin de la commande si vous souhaitez l'activer.",
    " ",
  ],
  scp: [
    "Utilisation: scp [filename ...] [target server]",
    " ",
    "Copiez le(s) fichier(s) spécifié(s) du serveur actuel vers le serveur cible. ",
    "Cette commande ne fonctionne que pour les fichiers de script (extension .script ou .js), les fichiers de littérature (extension .lit), ",
    "et des fichiers texte (extension .txt). ",
    "Le deuxième argument transmis doit être le nom d'hôte ou l'adresse IP du serveur cible. Exemples :",
    " ",
    "    scp foo.script n00dles",
    " ",
    "    scp foo.script bar.script n00dles",
    " ",
  ],
  sudov: ["Utilisation: sudov", " ", "Affiche si vous avez ou non un accès root à la machine actuelle", " "],

  tail: [
    "Utilisation: tail [script name] [args...]",
    " ",
    "Affiche les journaux dynamiques pour le script spécifié par le nom du script et les arguments. Chaque argument doit être séparé ",
    "par un espace. N'oubliez pas qu'un script en cours d'exécution est identifié de manière unique à la fois par son nom et par les arguments qui ont été utilisés ",
    "pour l'exécuter. Ainsi, si un script a été exécuté avec les arguments suivants : ",
    " ",
    "    run foo.script 10 50000",
    " ",
    "Ensuite, pour vérifier ses journaux avec 'tail', les mêmes arguments doivent être utilisés : ",
    " ",
    "    tail foo.script 10 50000",
    " ",
  ],
  top: [
    "Utilisation: top",
    " ",
    "Affiche une liste de tous les scripts en cours d'exécution sur le serveur actuel ainsi que leur nombre de threads et combien ",
    "La RAM qu'ils utilisent au total.",
    " ",
  ],
  unalias: [
    "Utilisation: unalias [alias name]",
    " ",
    "Supprime l'alias spécifié. Notez que les guillemets doubles sont obligatoires. ",
    " ",
    "A titre d'exemple, si un alias a été déclaré en utilisant :",
    " ",
    ' alias r="exécuter"',
    " ",
    "Ensuite, il pourrait être supprimé en utilisant :",
    " ",
    " unalias r",
    " ",
    "Il n'est pas nécessaire de faire la différence entre les alias globaux et non globaux lors de l'utilisation de 'unalias'",
    " ",
  ],
  vim: TemplatedHelpTexts.scriptEditor("vim"),
  weaken: [
    "Utilisation: weaken",
    " ",
    "Réduit le niveau de sécurité du serveur actuel. Diminue le temps nécessaire à toutes les opérations sur ce serveur.",
    "Nécessite un accès root. Voir la page wiki pour les mécanismes de piratage.",
    " ",
  ],
  wget: [
    "Utilisation: wget [url] [target file]",
    " ",
    "Récupère les données d'une URL et les télécharge dans un fichier sur le serveur actuel. Les données peuvent uniquement ",
    "être téléchargé dans un script (.script ou .js) ou un fichier texte (.txt). Si le fichier existe déjà, ",
    "il sera écrasé par cette commande.",
    " ",
    "Notez qu'il ne sera pas possible de télécharger des données depuis de nombreux sites Web car ils ne le permettent pas",
    "partage de ressources cross-origin (CORS). Exemple :",
    " ",
    "    wget https://raw.githubusercontent.com/bitburner-official/bitburner-src/master/README.md game_readme.txt",
    " ",
  ],
};
